
# Makefile.zfs -- FreeBSD Makefile remainser for ZFS modules
#
# $Id: Makefile.zfs,v 1.2 2008/05/09 12:53:13 abe Exp $

CFLAGS+=-D_SOLARIS_C_SOURCE
CFLAGS+=${DEBUG}
CFLAGS+=-I${OPENSOLARIS}/compat/opensolaris
CFLAGS+=-I${OPENSOLARIS}/contrib/opensolaris/uts/common/fs/zfs
CFLAGS+=-I${OPENSOLARIS}/contrib/opensolaris/uts/common/zmod
CFLAGS+=-I${OPENSOLARIS}/contrib/opensolaris/uts/common
CFLAGS+=-I${OPENSOLARIS}/contrib/opensolaris/common/zfs
CFLAGS+=-I${OPENSOLARIS}/contrib/opensolaris/common
CFLAGS+=-I${.CURDIR}/usr/src/include
CFLAGS+=-I`pwd`

dnode2.o:	dzfs.h dnode2.c
